---
sudo: required
services: docker
dist: xenial
language: python
python:
  - 3.7
jobs:
  include:
  - name: "AWS Test"
    if: fork IS false
    env: TYPE=aws
  - name: "Docker Test"
    env: TYPE=docker
  - name: "Docs Test"
    env: TYPE=docs
before_install:
  - |
    if [ "${TYPE}" == "docker" ]; then
      docker pull centos/systemd
      if [[ "${TRAVIS_PULL_REQUEST}" == "false" || "${TRAVIS_PULL_REQUEST_SLUG}" == "MindPointGroup/RHEL7-STIG" ]]; then
        docker login -u=$RHR_USER -p=$RHR_TOKEN registry.redhat.io
        docker pull registry.redhat.io/rhel7:latest
        (cd molecule/docker; docker build --build-arg rhn_user=$RHN_USERNAME --build-arg rhn_pass=$RHN_PASSWORD -t  molly .)
      else
        sed -i '/- name: RHEL/,/- docker/d' ./molecule/docker/molecule.yml
      fi
    fi
install:
  - |
    if [ "${TYPE}" == "docs" ]; then
      (cd doc; pip3 install -r requirements.txt)
    else
      pip3 install -r tests/ci-requirements.txt
    fi
script:
  - |
    if [ "${TYPE}" == "docs" ]; then
      (cd doc; make clean; make html)
    else
      molecule --base-config base-molecule.yml test --scenario-name $TYPE
    fi
