---
# tasks/audit_command.yml

- name: "MEDIUM | RHEL-07-{{ item.id }} | {{ audit_present | ternary('PATCH', 'REVERT') }} | The Red Hat Enterprise Linux operating system must audit all uses of the {{ item.path | basename }} command."
  lineinfile:
      path: "/etc/audit/rules.d/rhel7stig_commands.rules"
      create: yes
      owner: root
      group: root
      mode: 0600
      line: "{{ item.trivial | default(false) | ternary(trivial_audit, normal_audit) }}"
      state: "{{ audit_present | ternary('present', 'absent') }}"
  vars:
      trivial_audit: "-w {{ item.path }} -p x -F auid!=4294967295 -k {{ item.key }}"
      normal_audit: "-a always,exit -F path={{ item.path }} -F auid>=1000 -F auid!=4294967295 -k {{ item.key }}"
      audit_present: "{{ item.create | default(vars['rhel_07_' + item.id]) }}"
  notify: restart auditd
