---
- name: "LOW | RHEL-07-020200 | PATCH | The Red Hat Enterprise Linux operating system must remove all software components after updated versions have been installed."
  lineinfile:
      dest: /etc/yum.conf
      regexp: ^#?clean_requirements_on_remove
      line: clean_requirements_on_remove=1
      insertafter: '\[main\]'
  when: rhel_07_020200
  tags:
      - RHEL-07-020200

- name: "LOW | RHEL-07-020300 | The Red Hat Enterprise Linux operating system must be configured so that all Group Identifiers (GIDs) referenced in the /etc/passwd file are defined in the /etc/group file."
  block:
      - name: "LOW | RHEL-07-020300 | PATCH | Check /etc/passwd entries"
        shell: pwck -r | grep 'no group' | awk '{ gsub("[:\47]",""); print $2}'
        changed_when: no
        failed_when: no
        check_mode: no
        register: passwd_gid_check

      - name: "LOW | RHEL-07-020300 | PATCH | Print warning about users with invalid GIDs missing GID entries in /etc/group"
        debug:
            msg: "WARNING: The following users have non-existent GIDs: {{ passwd_gid_check.stdout_lines | join (', ') }}"
        changed_when:
            - rhel7stig_audit_complex
        when: passwd_gid_check.stdout_lines
  when:
      - rhel_07_020300
      - rhel7stig_complex
  tags:
      - RHEL-07-020300
      - complexity-high
      - passwd

- name: |
      "LOW | RHEL-07-021022 | PATCH | The Red Hat Enterprise Linux operating system must mount /dev/shm with the nodev option."
      "LOW | RHEL-07-021023 | PATCH | The Red Hat Enterprise Linux operating system must mount /dev/shm with the nosuid option."
      "LOW | RHEL-07-021024 | PATCH | The Red Hat Enterprise Linux operating system must mount /dev/shm with the noexec option."
  mount:
      path: /dev/shm
      state: mounted
      src: "{{ dev_shm_mount.device | default('tmpfs') }}"
      fstype: "{{ dev_shm_mount.fstype | default('tmpfs') }}"
      opts: "{{ dev_shm_mount_opts }}"
  when: rhel_07_021022 or rhel_07_021023 or rhel_07_021024
  vars:
      dev_shm_mount: "{{ ansible_mounts | json_query('[?mount == `/dev/shm`] | [0]') }}"
      dev_shm_mount_opts: "{{ dev_shm_mount.options | default('defaults') }},nodev,nosuid{{ (rhel_07_021024) | ternary(',noexec', '') }}"
  tags:
      - RHEL-07-021022
      - RHEL-07-021023
      - RHEL-07-021024

- name: "LOW | RHEL-07-021310 | PATCH | The Red Hat Enterprise Linux operating system must be configured so that a separate file system is used for user home directories (such as /home or an equivalent)."
  debug:
      msg: "WARNING: /home is not mounted on a separate partition"
  changed_when:
      - rhel7stig_audit_complex
  when:
      - not rhel7stig_system_is_container
      - rhel_07_021310
      - rhel7stig_complex
      - ansible_mounts | selectattr('mount', 'match', '^/home$') | list | length == 0
  tags:
      - RHEL-07-021310
      - complexity-high
      - mount
      - home

- name: "LOW | RHEL-07-021320 | PATCH | The Red Hat Enterprise Linux operating system must use a separate file system for /var."
  debug:
      msg: "WARNING: /var is not mounted on a separate partition"
  changed_when:
      - rhel7stig_audit_complex
  when:
      - not rhel7stig_system_is_container
      - rhel_07_021320
      - rhel7stig_complex
      - ansible_mounts | selectattr('mount', 'match', '^/var$') | list | length == 0
  tags:
      - RHEL-07-021320
      - complexity-high
      - mount
      - var

- name: "LOW | RHEL-07-021330 | PATCH | The Red Hat Enterprise Linux operating system must use a separate file system for the system audit data path."
  debug:
      msg: "WARNING: /var/log/audit is not mounted on a separate partition"
  changed_when:
      - rhel7stig_audit_complex
  when:
      - not rhel7stig_system_is_container
      - rhel_07_021330
      - rhel7stig_complex
      - ansible_mounts | selectattr('mount', 'match', '^/var/log/audit$') | list | length == 0
  tags:
      - RHEL-07-021330
      - complexity-high
      - mount
      - auditd

- name: "LOW | RHEL-07-021340 | PATCH | The Red Hat Enterprise Linux operating system must use a separate file system for /tmp (or equivalent)."
  systemd:
      name: tmp.mount
      daemon_reload: "{{ rhel7stig_systemd_daemon_reload }}"
      enabled: yes
      masked: no
      state: "{{ rhel7stig_service_started }}"
  when:
      - rhel_07_021340
      - not (rhel7stig_system_is_chroot and rhel7stig_system_is_container)
      - ansible_mounts | selectattr('mount', 'match', '^/tmp$') | list | length == 0
  tags:
      - RHEL-07-021340
      - mount
      - tmp

- name: "LOW | RHEL-07-021600 | PATCH | The Red Hat Enterprise Linux operating system must be configured so that the file integrity tool is configured to verify Access Control Lists (ACLs)."
  command: "true"
  changed_when: no
  when: rhel_07_021600
  tags:
      - RHEL-07-021600
      - notimplemented

- name: "LOW | RHEL-07-021610 | PATCH | The Red Hat Enterprise Linux operating system must be configured so that the file integrity tool is configured to verify extended attributes."
  command: "true"
  changed_when: no
  when: rhel_07_021610
  tags:
      - RHEL-07-021610
      - notimplemented

- name: "LOW | RHEL-07-040000 | PATCH | The Red Hat Enterprise Linux operating system must limit the number of concurrent sessions to 10 for all accounts and/or account types."
  lineinfile:
      state: present
      dest: /etc/security/limits.conf
      insertbefore: '^# End of file'
      regexp: '^\*.*maxlogins'
      line: '*               hard    maxlogins       {{ rhel7stig_maxlogins }}'
  when: rhel_07_040000
  tags:
      - RHEL-07-040000

- name: "LOW | RHEL-07-040530 | The Red Hat Enterprise Linux operating system must display the date and time of the last successful account logon upon logon."
  block:
      - name: "LOW | RHEL-07-040530 | Update pam_lastlog control to satisfy benchmark."
        pamd:
            name: postlogin
            type: session
            control: "{{ old_control }}"
            new_control: "{{ default_control }}"
            module_path: pam_lastlog.so
            state: updated

      - name: "LOW | RHEL-07-040530 | The Red Hat Enterprise Linux operating system must display the date and time of the last successful account logon upon logon."
        pamd:
            name: postlogin
            state: args_absent
            type: session
            control: "{{ item }}"
            module_path: pam_lastlog.so
            module_arguments: silent
        with_items:
            - '[default=1]'
            - "{{ default_control }}"

      - name: "MEDIUM | RHEL-07-010270 | PATCH | Remove old remediation"
        blockinfile:
            state: absent
            path: /etc/pam.d/postlogin
            insertafter: '^# User changes will be destroyed'
            block: |
                ### RHEL-07-040530 ###
                session required pam_lastlog.so showfailed
  vars:
      default_control: "{{ rhel7stig_workaround_for_disa_benchmark | ternary('required', 'optional') }}"
      old_control: "{{ rhel7stig_workaround_for_disa_benchmark | ternary('optional', 'required') }}"
  when: rhel_07_040530
  tags:
      - RHEL-07-040530
      - pamd

- name: "LOW | RHEL-07-040600 | PATCH | For Red Hat Enterprise Linux operating systems using DNS resolution, at least two name servers must be configured."
  command: "true"
  changed_when: no
  when: rhel_07_040600
  tags:
      - RHEL-07-040600
      - notimplemented
