---
- name: Converge
  hosts: rhel7-stig-local
  connection: docker
  pre_tasks:
    - name: install packages for testing under docker
      yum:
        name:
          - selinux-policy
          - libselinux-python
          - openssh-server
          - which
          - sudo
        state: present

    - name: Generate hostkey
      systemd:
        name: sshd
        state: started
        enabled: true


  roles:
    - role: ../../RHEL7-STIG
      rhel7stig_system_is_container: yes
